version: '3.8'

services:
  webapp:
    build: https://github.com/hmasystemer/docker_compose_build.git # Git repo link
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - ./local-index.html:/usr/share/nginx/html/index.html  # Mount a local file into the container
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

